#SamL10 Hex-File post-processor
#Based on the following hexmate line
#hexmate ${ImageDir}\SamL10_Touch.X.production.unified.hex -O${ImageDir}\SamL10_Touch.X.production.unified.crc32.hex -LOGFILE=${ImageDir}\hexmate.hxl --sla=0x7FFC -FILL=0xFFFF@0x0:0x7FFB -CK=0x1000-0x7FFB@0x7FFC+FFFFFFFFw-4g-5p04C11DB7
#postProcess.py --inHex ${ImageDir}\SamL10_Touch.X.production.unified.hex --printInputSegments --outAppC ../../../ESP32/main/import/BL_saml10_firmware_data.h  --outFactory ${ImageDir}\SamL10_Touch.X.production.unified.crc32.hex  --printOutputSegments

import argparse
import crcmod
import datetime
from intelhex import IntelHex
from intelhex.compat import array_tobytes
import os

FLASH_START = 0x0
FLASH_END = 32768
BOOT_START = 0x0
BOOT_END = 0x1000
APP_START = BOOT_END
APP_END = FLASH_END - 4
CRC_START = APP_END
CRC_END = FLASH_END
CRC_SIZE = CRC_END - CRC_START

parser = argparse.ArgumentParser(
                    prog='SamPostProcess',
                    description='Adjusts hex file, removing BOCOR and adding CRC')
parser.add_argument('--inHex', type=str, required=True, nargs='+', help='input hex file. ')
parser.add_argument('--printInputSegments', action='store_true')
parser.add_argument('--printOutputSegments', action='store_true')
parser.add_argument('--pruneBocor', action='store_true')
parser.add_argument('--trimAppCrc', action='store_true')
parser.add_argument('--outAppC', type=argparse.FileType('w', encoding='latin-1'), help='output C header.')
parser.add_argument('--outFactory', type=argparse.FileType('w', encoding='latin-1'), help='output factory hex.')
args = parser.parse_args()

ih = IntelHex()
for inHex in args.inHex:
    #'dist/default/production/SamL10_Touch.X.production.unified.hex'
    print("Loading:", inHex)
    temp = IntelHex(inHex)
    ih.merge(temp, overlap='error')

if args.printInputSegments:
    print("Printing Input Segments:")
    for segment in ih.segments():
        print('\t' + hex(segment[0]) + ":" + hex(segment[1]))

if args.pruneBocor:
    print("Pruning BOCOR flash...")
    ihNew = IntelHex()
    BOCOR_START = 0x0080C000
    BOCOR_END = 0x0080C000 + 256
    for segment in ih.segments():
        if segment[0] >= BOCOR_START and segment[0] < BOCOR_END:
            print("\tPruning:" + hex(segment[0]) + ":" + hex(segment[1]))
            continue
        #print("\tkeeping: " + hex(segment[0]) + ":" + hex(segment[1]))
        for i in range(segment[0], segment[1]):
            ihNew[i] = ih[i]
    ih = ihNew

#Fill empty ranges in flash
for i in range(FLASH_START, FLASH_END):
    if ih[i] == 0xFF:
        ih[i] = 0xFF

if args.trimAppCrc:
    print("Trimming Application CRC area from(", hex(APP_START), ',', hex(APP_END), ')', end='')
    for i in range(APP_END, APP_START, -4):
        if ih[i] != 0xFF or ih[i+1] != 0xFF or ih[i+2] != 0xFF or ih[i+3] != 0xFF:
            break;
        APP_END = i
        CRC_START = i
        CRC_END = i + CRC_SIZE
    print(" to (", hex(APP_START), ',', hex(APP_END), ')')


print("Generating CRC of application segment(" + hex(APP_START) + ":" + hex(APP_END) + ")...", end='')
crc_func = crcmod.mkCrcFun(0x104C11DB7, xorOut=0)
crc_data = bytearray()
for i in range(APP_START, APP_END):
    crc_data.append(ih[i])
#Test input for SamL10, should equal 0x340BC6D9
#crc_data = b'123456789'
crc_value = crc_func(crc_data) & 0xFFFFFFFF
print("0x{0:08x}".format(crc_value))

print("Appending CRC...", end='')
ih[CRC_START + 0] = (crc_value >>  0) & 0xFF
ih[CRC_START + 1] = (crc_value >>  8) & 0xFF
ih[CRC_START + 2] = (crc_value >> 16) & 0xFF
ih[CRC_START + 3] = (crc_value >> 24) & 0xFF
print("done")


if args.printOutputSegments:
    print("Printing Output Segments:")
    for segment in ih.segments():
        print('\t' + hex(segment[0]) + ":" + hex(segment[1]))

if args.outAppC != None:
    #args.outAppC = open('../../../ESP32/main/import/BL_shared_headers_firmware_data.h','w')
    print("Generating source code block...")
    datestr = str(datetime.date.today())
    commentPaths = [x.replace(os.sep, "/") for x in args.inHex]
    print("/*AutoGenerated by postProcess.py from " + ",".join(commentPaths) + "*/", file=args.outAppC)
    print("static const uint8_t sensorHubFirmwareData[]=", file=args.outAppC)
    print("{", file=args.outAppC)
    for i in range(APP_START,CRC_END):
        if(i % 16) == 0:
            print('\n  ', end='', file=args.outAppC)
        print("0x{0:02x}".format(ih[i]), ",", sep='', end='', file=args.outAppC)
    print("\n};", file=args.outAppC)

if args.outFactory != None:
    ih.write_hex_file(args.outFactory)